backend:
  name: git-gateway
  branch: master

media_folder: "static/uploads"
public_folder: "uploads"

collections:
  - name: "coding"
  label: 'Coding'
  folder: "content/coding"
  create: true
  slug: "{{year}}-{{slug}}"
  fields: 
    - {label: "Title", name: 'title', widget: "string"}