backend:
  name: github
  repo: jd-fillmore/infused-gridsome

local_backend: true

media_folder: "img"
public_folder: "../img"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "date" }
      - { name: slug, label: Slug, required: true, widget: string }
      - { label: "Excerpt", name: "excerpt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
